print-status: False
api:
    name: TelegramManagerApi
    version: 0.0.2
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    session:
        secret: ${SESSION_SECRET:default}
    api-key:
        secret: ${API_KEY_SECRET:default}
    security:
        secret: ${SECURITY_SECRET:default}
    server:
        scheme: http
        host: 0.0.0.0
        port: 6090
        base-url: /telegram-manager-api
    scheduler:
        time-zone: ${SCHEDULER_TIMEZONE:Brazil/East}
        enable: ${ENABLE_SCHEDULER_API:True}
    listener:
        enable: ${ENABLE_LISTENER_API:True}
    emitter:
        enable: ${ENABLE_EMITER_API:True}

telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN:test}
    chat-id: ${TELEGRAM_CHAT_ID}

queue-manager-api:
    base-url: ${QUEUE_MANAGER_API_HOST}/queue-manager-api
    api-key: ${QUEUE_MANAGER_API_API_KEY}
    api-notifications:
        queue-key: ${API_NOTIFICATIONS_QUEUE_KEY}
        emitter:
            timeout: 2
        listener:
            timeout: 2
    send-telegram:
        queue-key: ${SEND_TELEGRAM_QUEUE_KEY}
        emitter:
            timeout: 2
    hit-shift:
        queue-key: ${HIT_SHIFT_QUEUE_KEY}
        emitter:
            timeout: 2
    hit-shift-now:
        queue-key: ${HIT_SHIFT_NOW_QUEUE_KEY}
        emitter:
            timeout: 2

shift-manager-api:
    base-url: ${SHIFT_MANAGER_API_HOST}/shift-manager-api
    api-key: ${SHIFT_MANAGER_API_API_KEY}
    timeout: 6


the-news-api:
    base-url: ${THE_NEWS_API_HOST}/the-news-api
    api-key: ${THE_NEWS_API_API_KEY}
    timeout: 20

swagger:
    # schemes: [${api.server.scheme}] ###- bug
    # host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
    info:
        # title: ${api.name} ###- commented to make use of auto title and auto description
        # description: Shift Api
        version: ${api.version}
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
