print-status: False

api:
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

queue-manager-api:
    base-url: ${QUEUE_MANAGER_API_HOST}:6931/queue-manager-api

shift-manager-api:
    base-url: ${SHIFT_MANAGER_API_HOST}:5095/shift-manager-api

swagger:
    schemes: [${api.server.scheme}] ###- bug
    host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
