print-status: False
api:
    name: TelegramManagerApi
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/SamuelJansen/
        extension: git

    session:
        secret: ${SESSION_SECRET:default}
    api-key:
        secret: ${API_KEY_SECRET:default}
    security:
        secret: ${SECURITY_SECRET:default}
    server:
        scheme: http
        host: 0.0.0.0
        port: 6089
        base-url: /telegram-manager-api
    scheduler:
        enable: ${ENABLE_SCHEDULER_API:True}
    listener:
        enable: ${ENABLE_LISTENER_API:True}
    emitter:
        enable: ${ENABLE_EMITER_API:True}

telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN:test}

aix-sports:
    championship:
        base-url: ${AIX_SPORTS_CHAMPIONSHIP_BASE_URL:default}
        timeout: 60

swagger:
    # schemes: [${api.server.scheme}] ###- bug
    # host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
    info:
        # title: ${api.name} ###- commented to make use of auto title and auto description
        # description: Shift Api
        version: 0.0.1
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Samuel Jansen
            email: samuel.jansenn@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
